//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quinto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoFutbolista
    {
        public int equipoID { get; set; }
        public int futbolistaID { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    
        public virtual Equipo Equipoes { get; set; }
        public virtual Futbolistas Futbolistas { get; set; }
    }
}
